### ISSUE TITLE
Make it clear that post-installation step is needed

### ISSUE THREAD

**Issue by mudrd8mz** [dthies/moodle-block_deft#1]
When installing the plugin, the New settings page may suggest there is not much to be configured for the block. It took me a while to realise I had to go back to block's settings in the site administration to actually activate the integration with deftly.us.

It might help to extend the README and the plugin description at https://moodle.org/plugins/block_deft to make it clear that a post-installation step is needed to activate the integration with the service.

**Comment by mudrd8mz** [comment]
Hmm. Still no luck to get it actually auto-update :-(

I also found that I probably have to go to Plugins > Activity modules > External tool > Manage tools and activate the tool? But even then, the block does not auto-update.

Could it be a browser thing? Should there be a test for the websockets support or so?

**Comment by dthies** [comment]
I found an inconsistency in expiration times of the authentication times. It should be fixed now. Docs are updated to make the registration more clear.

**Comment by dthies** [comment]
I added a notice to the report on the task dashboard that appears to the system admin along with the usage information. It has a link to the setting page to correct the problem. They should see it there if they miss the other instructions.
