### ISSUE TITLE
SQL SELECT inside foreach loop

### ISSUE THREAD

**Issue by mudrd8mz** [dthies/moodle-block_deft#2]
In the `block_deft\cache\results::load_many_for_cache()` the SQL SELECT queries are executed inside the `foreach` loop. In general, this is always better to avoid and use https://moodledev.io/docs/apis/core/dml#get_in_or_equal instead.

**Comment by dthies** [comment]
@mudrd8mz I think you are correct, I did not write this but copied it from core e.g. overrides, messages and course image caches use same code. I never call this method (only get) so I just left this as a fall back in case. I suspect that there still might be cases where it might be used in the core examples and might improve performance there.

**Comment by dthies** [comment]
I did a quick grep of the code areas I mentioned for get_many and did not find any uses so I would assume that the code is okay there for the same reason.

**Comment by mudrd8mz** [comment]
OK, I agree. Thanks.
