### ISSUE TITLE
Re-uses block_rss_client capabilities without explicit dependency

### ISSUE THREAD

**Issue by mudrd8mz** [dthies/moodle-block_deft#4]
https://github.com/dthies/moodle-block_deft/blob/329457e42134bbc057ac2eb2348e46954b790e08/manage.php#L48-L51 re-uses the other block's capabilities.

1. Is this intentional? Would not it be better to have a dedicated capability for this and eventually make use of `clonepermissionsfrom` (https://moodledev.io/docs/apis/subsystems/access) to make the initial setup easier?
2. If is it intentional, it would be better / safer to have the other block explicitly mentioned as a dependency, even when it is a standard one.

**Comment by dthies** [comment]
I copied that and meant to change it the corresponding deft capabilities. I have it fixed now and will upload it.
